# Étape 1 : Build with Maven
FROM maven:3.9.11-eclipse-temurin-21 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Étape 2 : Minimal final image
FROM eclipse-temurin:21-jre-alpine
RUN addgroup -S backend && adduser -S backend -G backend
USER backend:backend

# Copy generated JAR
COPY --from=build /app/target/*.jar app.jar

ENTRYPOINT ["java", "-jar", "/app.jar"]
