
version: "3.9"
services:
  db:
    image: docker.io/postgres:17
    container_name: "demo-spring_keycloak_vuejs-postgres"
    ports:
      - "5432:5432"
    env_file:
      - .env.database
    restart: unless-stopped
