<script setup>
// import TheWelcome from '@/components/TheWelcome.vue'
import ApiPublicData from '@/components/ApiPublicData.vue'
import keycloak from '@/config/keycloak'
</script>

<template>
  <main>
    <h1>Welcome to the Spring Vue Postgres Keycloak (<i>SVPK</i>) Architecture</h1>

    <hr />

    <button v-if="keycloak.authenticated" @click="keycloak.logout()">Log out</button>
    <button v-else @click="keycloak.login()">Login</button>

    <h1>Public data from API</h1>
    <ApiPublicData />

    <!-- Generated by Vue -->
    <!-- <hr />
    <h1>Content from Vue</h1>
    <TheWelcome /> -->
  </main>
</template>
