# This properties file *overrides* certain values in the application.properties file for testing purposes

# Application
spring.application.name=backend-tests

# H2 Database (overrides Postgres config)
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driver-class-name=org.h2.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=false
