CREATE TABLE helloworlds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hello_message VARCHAR(256) NOT NULL UNIQUE,

    -- Audit and versioning
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastmodified_at TIMESTAMP,
    version INTEGER
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sub VARCHAR(36) NOT NULL UNIQUE,
    surname VARCHAR(256) NOT NULL UNIQUE,

    -- Audit and versioning
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastmodified_at TIMESTAMP,
    version INTEGER
);
