
version: "3.9"
services:
  oauth:
    image: quay.io/keycloak/keycloak:26.4
    container_name: "keycloak-prod"
    depends_on:
      - db
      - adminer
    ports:
      - "8181:8080"
    command: ["start-dev"]
    env_file:
      - .env.keycloak
    restart: unless-stopped
  db:
    image: docker.io/postgres:18
    container_name: "keycloak-prod-db"
    ports:
      - "5432:5432"
    volumes:
      - "/MOUNT_DATA_PATH:/var/lib/postgresql/data" # Edit for your custom path
    restart: always
  adminer:
    image: docker.io/adminer:5
    container_name: "keycloak-prod-db-adminer"
    depends_on:
      - db
    env_file:
      - .env.keycloak-db
    ports:
      - "8182:8080"
    restart: always
